package com.bytejoey.polygonclip.num;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Oracle tests for the robust orientation predicate ported from
 * robust-predicates v3.0.2 (upstream/robust-predicates/orient2d.js).
 *
 * Sign convention (per the JS implementation, which negates Shewchuk's
 * determinant): det = (ay - cy) * (bx - cx) - (ax - cx) * (by - cy).
 * In a y-up coordinate system this returns a POSITIVE value when a, b, c
 * occur in CLOCKWISE order (c right of the directed line a->b), a NEGATIVE
 * value for COUNTERCLOCKWISE order, and exactly zero when collinear.
 *
 * Expected values below were generated by executing the upstream JS
 * (upstream/dist/polygon-clipping.umd.js, built from the same sources)
 * under Node.
 */
class OrientTest {

    @Nested
    @DisplayName("collinear -> exact zero")
    class Collinear {

        @Test
        @DisplayName("simple diagonal collinear triple")
        void simpleDiagonal() {
            assertEquals(0.0, Orient.orient2d(0, 0, 1, 1, 2, 2), 0.0);
        }

        @Test
        @DisplayName("horizontal collinear triple")
        void horizontal() {
            assertEquals(0.0, Orient.orient2d(0, 0, 1, 0, 2, 0), 0.0);
        }

        @Test
        @DisplayName("large-coordinate collinear triple where naive FP is unreliable")
        void largeCoordinates() {
            assertEquals(0.0, Orient.orient2d(1e17, 1e17, 2e17, 2e17, 3e17, 3e17), 0.0);
        }
    }

    @Nested
    @DisplayName("sign convention (positive = clockwise in y-up coords)")
    class SignConvention {

        @Test
        @DisplayName("counterclockwise triple (0,0),(1,0),(0,1) -> negative")
        void counterclockwiseIsNegative() {
            double res = Orient.orient2d(0, 0, 1, 0, 0, 1);
            assertTrue(res < 0, "expected negative for CCW, got " + res);
            assertEquals(-1.0, res, 0.0);
        }

        @Test
        @DisplayName("clockwise mirror (0,0),(0,1),(1,0) -> positive")
        void clockwiseIsPositive() {
            double res = Orient.orient2d(0, 0, 0, 1, 1, 0);
            assertTrue(res > 0, "expected positive for CW, got " + res);
            assertEquals(1.0, res, 0.0);
        }
    }

    @Nested
    @DisplayName("near-collinear robustness (adaptive path)")
    class NearCollinear {

        private static final double ULP = Math.ulp(1e-12);

        @Test
        @DisplayName("base collinear triple at 1e-12 scale -> exact zero")
        void baseIsExactlyZero() {
            assertEquals(0.0, Orient.orient2d(0, 0, 1e-12, 1e-12, 2e-12, 2e-12), 0.0);
        }

        @Test
        @DisplayName("middle point y +1 ulp -> positive (b above the a->c line, right turn = clockwise)")
        void plusUlpIsPositive() {
            double res = Orient.orient2d(0, 0, 1e-12, 1e-12 + ULP, 2e-12, 2e-12);
            assertTrue(res > 0, "expected positive, got " + res);
            // exact result: 2 * 1e-12 * ulp (verified against the JS implementation)
            assertEquals(2e-12 * ULP, res, 0.0);
        }

        @Test
        @DisplayName("middle point y -1 ulp -> negative (the other side)")
        void minusUlpIsNegative() {
            double res = Orient.orient2d(0, 0, 1e-12, 1e-12 - ULP, 2e-12, 2e-12);
            assertTrue(res < 0, "expected negative, got " + res);
            assertEquals(-(2e-12 * ULP), res, 0.0);
        }
    }

    @Nested
    @DisplayName("antisymmetry: orient2d(a,b,c) == -orient2d(b,a,c)")
    class Antisymmetry {

        private void checkAntisymmetric(double ax, double ay, double bx, double by, double cx, double cy) {
            double ab = Orient.orient2d(ax, ay, bx, by, cx, cy);
            double ba = Orient.orient2d(bx, by, ax, ay, cx, cy);
            assertEquals(-ba, ab, 0.0);
        }

        @Test
        @DisplayName("small integer triple")
        void smallIntegers() {
            checkAntisymmetric(2, 3, 7, 1, 4, 8);
            assertEquals(-29.0, Orient.orient2d(2, 3, 7, 1, 4, 8), 0.0);
        }

        @Test
        @DisplayName("mixed-sign fractional triple")
        void mixedSignFractions() {
            checkAntisymmetric(-3.5, 2.25, 1.125, -7.75, 9.5, 0.5);
        }

        @Test
        @DisplayName("non-representable decimal triple")
        void decimalTriple() {
            checkAntisymmetric(0.1, 0.2, 0.3, 0.4, 0.5, 0.61);
        }

        @Test
        @DisplayName("large-magnitude triple")
        void largeMagnitudes() {
            checkAntisymmetric(1e8, -2e8, 3.5e7, 1.25e8, -9e7, 4e7);
        }

        @Test
        @DisplayName("near-collinear adaptive-path triple")
        void nearCollinearTriple() {
            checkAntisymmetric(0, 0, 1e-12, 1e-12 + Math.ulp(1e-12), 2e-12, 2e-12);
        }
    }

    @Nested
    @DisplayName("determinism")
    class Determinism {

        @Test
        @DisplayName("repeated adaptive-path calls return bit-identical results")
        void adaptivePathIsDeterministic() {
            double first = Orient.orient2d(0, 0, 1e-12, 1e-12 + Math.ulp(1e-12), 2e-12, 2e-12);
            for (int i = 0; i < 10; i++) {
                double again = Orient.orient2d(0, 0, 1e-12, 1e-12 + Math.ulp(1e-12), 2e-12, 2e-12);
                assertEquals(Double.doubleToLongBits(first), Double.doubleToLongBits(again));
            }
        }

        @Test
        @DisplayName("repeated fast-path calls return bit-identical results")
        void fastPathIsDeterministic() {
            double first = Orient.orient2d(-3.5, 2.25, 1.125, -7.75, 9.5, 0.5);
            for (int i = 0; i < 10; i++) {
                double again = Orient.orient2d(-3.5, 2.25, 1.125, -7.75, 9.5, 0.5);
                assertEquals(Double.doubleToLongBits(first), Double.doubleToLongBits(again));
            }
        }
    }
}
